routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('book','BookController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
   protected $table = 'book';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Book;

class BookController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    //show data
    $books = Book::all();
    return view('book.index',['books' => $books]);
  }
  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    //create view
    return view('book.create');
  }
  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
    //validation
    $this->validate($request, [
      'title'=>'required',
      'author'=>'required',
      'publisher'=>'required',
      'image'=>'required',
    ]);
    //create new data
    $book = new book;
    $book->title = $request->title;
    $book->author = $request->author;
    $book->publisher = $request->publisher;
    $book->image = $request->image;
    $book->save();
    return redirect()->route('book.index')->with('alert-success','Data has been saved!');
  }
  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $book = Book::findOrFail($id);
    //return to the view
    return view('book.edit', ['book'=> $book]);
  }
  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update(Request $request, $id)
  {
    //validation
    $this->validate($request, [
      'title'=>'required',
      'author'=>'required',
      'publisher'=>'required',
      'image'=>'required',
    ]);

    //create new data
    $book = Book::findOrFail($id);
    $book->title = $request->title;
    $book->author = $request->author;
    $book->publisher = $request->publisher;
    $book->image = $request->image;
    $book->save();
    return redirect()->route('book.index')->with('alert-success','Data has been saved!');
  }
  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    $book = Book::findOrFail($id);
    $book->delete();
    return redirect()->route('book.index')->with('alert-success','Data has been deleted!');
  }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/book/create.blade.php
<!--extends from the master layout-->
@extends('layouts/master')

<!-- section content page-->
@section('content')
  <div class="row">
    <div class="col-md-12">
      <h1>Create Book</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      {!! Form::open(['route'=>'book.store', 'method'=>'POST']) !!}
        @include('book.forms.book_form')
      {!! Form::close() !!}
    </div>
  </div>
@stop

resources/views/book/edit.blade.php
@extends('layouts/master')

<!-- section content page-->
@section('content')
  <div class="row">
    <div class="col-md-12">
      <h1>Edit Book</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      {!! Form::model($book,['route'=>['book.update', $book->id], 'method'=>'PUT']) !!}
         @include('book.forms.book_form')
      {!! Form::close() !!}
    </div>
  </div>
@stop

resources/views/book/forms/book_form.blade.php
<div class="form-group{{ ($errors->has('title')) ? $errors->first('title') : '' }}">
  {!! Form::label('title','Title:') !!}
  {!! Form::text('title',NULL,['class'=>'form-control','placeholder'=>'Insert a title']) !!}
  {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ ($errors->has('author')) ? $errors->first('author') : '' }}">
  {!! Form::label('author','Author:') !!}
  {!! Form::text('author',NULL,['class'=>'form-control','placeholder'=>'Insert a author']) !!}
  {!! $errors->first('author', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ ($errors->has('publisher')) ? $errors->first('publisher') : '' }}">
  {!! Form::label('publisher','Publisher:') !!}
  {!! Form::text('publisher',NULL,['class'=>'form-control','placeholder'=>'Insert a publisher']) !!}
  {!! $errors->first('publisher', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ ($errors->has('image')) ? $errors->first('image') : '' }}">
  {!! Form::label('image','Image:') !!}
  {!! Form::text('image',NULL,['class'=>'form-control','placeholder'=>'Insert a image']) !!}
  {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group">
  {!! Form::submit('Save',['class'=>'btn btn-primary']) !!}
</div>

resources/views/book/index.blade.php
<!--extends from the master layout-->
@extends('layouts/master')

<!-- section content page-->
@section('content')
  <div class="row">
    <div class="col-md-12">
      <a href="{{ route('book.create') }}" class="btn btn-info pull-right">Create New Book</a><br/><br/>
    </div>
  </div>
  <table class="table table-striped">
    <tr>
      <th>No.</th>
      <th>Title</th>
      <th>Author</th>
      <th>Publiched</th>
      <th>Image</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Actions</th>
    </tr>
    <?php $index = 1; ?>
    @foreach($books as $book)
      <tr>
        <td>{{ $index++ }}</td>
        <td>{{ $book->title }}</td>
        <td>{{ $book->author }}</td>
        <td>{{ $book->publisher }}</td>
        <td>{{ $book->image }}</td>
        <td>{{ $book->created_at }}</td>
        <td>{{ $book->updated_at }}</td>
        <td>
          <form action="{{ route('book.destroy',$book->id) }}" method="post">
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <a href="{{ route('book.edit', $book->id) }}" class="btn btn-primary">Edit</a>
            <input type="submit" class="btn btn-danger" value="Delete" onclick="return confirm('Are you sure?')">
          </form>
        </td>
      </tr>
    @endforeach
  </table>
@stop

resources/views/home.blade.php
<!--extends from the master layout-->
@extends('layouts/master')

<!-- section content page-->
@section('content')
    <div class="bg-image">
        <h1>Home Page - First Laravel Page</h1>
        <a href="{{ url('/book') }}">Manage Books ></a>
    </div>
@stop

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ config('app.locale') }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bookstore</title>
  <!-- add the styles -->
  <link rel="stylesheet" href="{{ asset('/css/app.css') }}">
  <link rel="stylesheet" href="{{ asset('/css/custom.css') }}">
</head>
<body>
  @include('sections.header')
  <div class="flex-center position-ref full-height">
    <div class="container">
      <div class="content">
        @yield('content')
      </div>
    </div>
  </div>
  @include('sections.footer')
</body>
</html>

resources/views/sections/footer.blade.php
<div class="footer">
   <div class="container">
      <div class="row">
         <div class="col-md-4">
            <p>Book store Test</p>
            <p>2017</p>
         </div>

         <div class="col-md-4">
            <p>San Jose</p>
            <p>Costa Rica</p>
         </div>
         <div class="col-md-4">
            <p><strong>Contact us</strong></p>
            <p>bookstore@test.com</p>
            <p>+506 34231212</p>
         </div>
      </div>
   </div>
</div>

resources/views/sections/header.blade.php
<div class="header">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1>Book Store Test</h1>
        <img src="{{ asset('/img/book-icon.png') }}" width="100" height="100"/>
      </div>

      <div class="col-md-4">
        <a href="{{ url('/book') }}">Log in ></a>
        <br/>
        <a href="{{ url('/book') }}">Manage Books ></a>
      </div>
    </div>
  </div>
</div>